Game: Game.java
	javac -J-Dfile.encoding=UTF-8 Game.java
Reversi: Reversi.java
	javac -J-Dfile.encoding=UTF-8 GReversi.java
Model: Model.java
	javac -J-Dfile.encoding=UTF-8 GModel.java
View: View.java
	javac -J-Dfile.encoding=UTF-8 GView.java
clean: 
	rm *.class
